### ISSUE TITLE
Grid system design

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/radium-component-library#1]
As a radium user, I want to be able to declaratively configure my application to use a responsive `radium-grid` system for layout.

## Principles

Based heavily on https://github.com/suitcss/components-grid

- Current version of that library is Flexbox
- Old version is `inline-block` (https://github.com/suitcss/components-grid/tree/1c91575e52573dfcc307309c34c3a63a8e888655)
- Flexbox layout computation is really slow.
- If it's not too much overhead, would prefer to support flexbox *or* inline-block so that users can opt out of flexbox for high performance layout.

## Theming

- Probably don't need theming for initial release.
- Most likely two types of theming in the future:
  1. Custom Media Queries
  2. Configurable gutter widths (default 24px between cells when gutters are enabled)

## Media Queries

These are pretty arbitrary, but I think make sense for a default set.

- SM: >= 320px
- MD: >= 640px
- LG: >= 960px
- XL: >= 1200px

### Sized Columns

```
<Grid>
  <Grid.Cell span={6/12} md={8/12}>
    Content!
  </Grid.Cell>

  <Grid.Cell span={6/12} md={4/12}>
    More Content!
  </Grid.Cell>
</Grid>
```

#### `align`

- `oneOf(['left', 'center', 'right'])`
- Default: `left`
- Horizontal cell alignment.

#### `vAlign`

- `oneOf(['top', 'middle', 'bottom'])`
- Default: `top`
- Vertical cell alignment.

#### `gutters`

- `bool`
- Default: `false`
- Adds gutters between grid cells.

### Potential Future Features

- Declare column widths using props on `Grid` component, all children automatically use the width from the parent (for convenience for equal cell widths).
- Auto column width support. Any children of a grid with `autoFit` enabled automatically fill the available space in a single line.

**Comment by arush** [comment]
1. agree with @ianobermiller the API should be lower level and not dependent on a grid.
2. flexbox goes both ways, there is a mainaxis and crossaxis, so vAlign wont make sense, since in a column scenario, the cross axis is left-to-right not top-to-bottom.
3. [angular-material](https://material.angularjs.org/latest/layout/alignment)'s flexbox API is the best one I've seen. i've written a full port of it in react. we use it with radium, and it is a joy to work with.
